### ISSUE TITLE
[Design QA] Recent Transaction Section doesn't extend properly

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#10]
Recent Transaction section should should fill the width of the screen like section above.

Devs:
<img width="498" alt="Screen Shot 2023-08-13 at 14 07 36" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/f6f51231-de36-4406-9295-bab4339f9589">

**Comment by thenerdcat** [comment]
Fixed ![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/27b1ce6d-f0d6-4c0d-93f5-bf3f0ceb858e)
![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/5e6236c0-c543-4a9f-a38f-421b45f100f9)
