### ISSUE TITLE
[BUG] Error should only show if there’s a value (>0) in the “value” field

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#100]
Error should only show if there’s a value (>0) in the “value” field

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/04f13d56-dff2-4b5f-b94d-47700a985644)

**Comment by krisbitney** [comment]
> Error should only show if there’s a value (>0) in the “value” field
> 
> <img alt="image.png" width="368" src="https://camo.githubusercontent.com/819cbc2a7a7ac71032e9e695f0756015c6d481e10ba40e1ddc8f9450fb951897/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424e6d5a435157633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d623565316235613264633238363862346138306639363461363332376339646666656138383032622f696d6167652e706e67">

The image link appears to be broken

**Comment by vldkhh** [comment]
verified 
<img width="1545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUwxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2a8393618b9f5e9034bbf692d7cf6e515261493/image.png" alt="image.png" />
