### ISSUE TITLE
[BUG] Social and web links do not work.

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#103]
Should only display if there’s a value, and open a new tab / page when clicked launching the appropriate asset.

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/56efe5c0-7aad-4c4a-ba8d-65978434a904)

**Comment by decentralauren** [comment]
@krisbitney content [can be found here. ](https://www.notion.so/serota/Pilot-dApp-Collective-Content-98cd3c62a39b4c7b9a8e066f14b6074e).

**Comment by vldkhh** [comment]
@krisbitney @decentralauren we should add socials to verify it

**Comment by vldkhh** [comment]
@L03TJ3

**Comment by L03TJ3** [comment]
@krisbitney 
on ViewCollective page I think it should use: https://github.com/GoodDollar/GoodCollective/blob/559ff7cc03be3a300e818fbf70421bfe6da78f1d/packages/app/src/subgraph/useSubgraphCollective.ts#L93

above query includes the socials, the other doesnt

**Comment by L03TJ3** [comment]
@decentralauren for Silvi's collective all socials are already set correctly.

@sirpy if a collective is created, is it still possible to update the socials after?

**Comment by krisbitney** [comment]
This is fixed in https://github.com/GoodDollar/GoodCollective/pull/121

**Comment by L03TJ3** [comment]
@vldkhh this is being released to dev as we speak

**Comment by L03TJ3** [comment]
Confirmed in call yesterday so closing
