### ISSUE TITLE
[BUG/Improvements] Pool Transactions not displaying

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#105]
- 1) No Transactions displayed
- 2) “Show More” appears when there are no transactions (should only appear after 25 transactions and the page truncates)

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/41019ebf-35d2-4d17-b82c-d8a19591410b)

**Comment by krisbitney** [comment]
I fixed the UI for recent transactions. Changes are in an open PR.

**Comment by krisbitney** [comment]
@sirpy @decentralauren @L03TJ3 One thing that is not clear to me: How do I get the data for the recent transactions? 

I could filter events in the smart contract, but that won't provide all of the necessary data. The amount donated in a transaction is not available on-chain. The smart contract instead knows about flow rates and the total amount a supporter has contributed.

**Comment by sirpy** [comment]
@krisbitney i'm not sure what you mean. all data should be from the subgraph.
If you mean right after user has performed an action and you want to display it for him then we need to either add some refresh for subgraph after user actions or add the action itself manually to the apollo cache

**Comment by krisbitney** [comment]
> @krisbitney i'm not sure what you mean. all data should be from the subgraph. If you mean right after user has performed an action and you want to display it for him then we need to either add some refresh for subgraph after user actions or add the action itself manually to the apollo cache

No, that is not what I mean. The subgraph is itself limited to on-chain data, so modifying the subgraph won't help.

According to the figma, the transaction items in the "recent transactions" list should have G$ amounts. How do I get those amounts?

**Comment by sirpy** [comment]
ok I see.
@decentralauren @patpedrosa What type of transactions is "recent transactions" supposed to show? donations? rewards distributions? probably the name should be changed to "recent X".

@krisbitney we'll need to update the subgraph. if it is donations we can add a DonationEvent record (create it in handleSupport) for rewards distribution txs we already have the EventData records

**Comment by krisbitney** [comment]
> ok I see. @decentralauren @patpedrosa What type of transactions is "recent transactions" supposed to show? donations? rewards distributions? probably the name should be changed to "recent X".
> 
> @krisbitney we'll need to update the subgraph. if it is donations we can add a DonationEvent record (create it in handleSupport) for rewards distribution txs we already have the EventData records

Yes, for sure. I can add events for donations. Still, the donation events won't have the amount donated because the contract knows only about flow rates. The amount the user donated is a function of flowRate and the duration of the flow.

**Comment by krisbitney** [comment]
I can have the amount in the donations be flowing rates, so they will show how much the user donated *so far* but not the total amount the user will donate through the transaction. What do you think?

**Comment by sirpy** [comment]
Well donations are either single or a flow rate.
both the donation amount and flow rate are known from the event.
if it is a flow rate then we can show next to the TX - 50G$/month 
if it is a single donation then just show the amount - 50G$

**Comment by vldkhh** [comment]
@decentralauren @patpedrosa Transaction pool is showing. What do we need to do with the "Show more" button? 

<img width="1543" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzNzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35b1c6f8baec58a6bd12e7570c7a63787394f2ae/image.png" alt="image.png" />

**Comment by L03TJ3** [comment]
@L03TJ3 make action item for loading of transaction list

**Comment by krisbitney** [comment]
> @L03TJ3 make action item for loading of transaction list.
> 
> * [ ]  - should show payouts / donated amounts

The transactions list already displays in the `ViewCollective` component, with payouts and donated amounts

**Comment by L03TJ3** [comment]
Unable to verify on UI but in code it shows it should show both donation + stewards payment so closing.

Show more button is defined here: https://github.com/GoodDollar/GoodCollective/issues/124

What has not been added was _if it is a flow rate then we can show next to the TX - 50G$/month_
not sure what to do with that
@patpedrosa @decentralauren

**Comment by krisbitney** [comment]
> Unable to verify on UI but in code it shows it should show both donation + stewards payment so closing.
> 
> Show more button is defined here: #124
> 
> What has not been added was _if it is a flow rate then we can show next to the TX - 50G$/month_ not sure what to do with that @patpedrosa @decentralauren

It looks like I misread that and made the donation amount a flowing rate. We can show all of the donation amounts in transactions in terms of a single unit (e.g. per month), but we cannot know whether the supporter intended to donate per day, per week, per month, etc.

**Comment by decentralauren** [comment]
Closing this ticket as the open item is in #167
