### ISSUE TITLE
[UX]: Switching account does not update UI

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#107]
**Describe the bug**
If you switch connected account it will keep showing the data from the first connect wallet.

## Reproduce:
1. connect a wallet.
2. go to profile page for example
3. switch connected account ( I switched through metamask as there is no way to switch from dapp UI)
4. profile page not updated

**Comment by L03TJ3** [comment]
@sirpy should this issue maybe turn into a more general one for adding wallet connect library?

**Comment by krisbitney** [comment]
The profile page is associated with the address in the URL, not the connected account. This allows you to, for example, click on a donor in the donor list and view their profile.

**Comment by L03TJ3** [comment]
Ah right, dumb.

not a bug so closing
