### ISSUE TITLE
[UX]: Reject token approval

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#108]
## Description
When you reject a token approval (either by chose or misclick) you cannot retry to do a new donation without having to navigate back/forth or refresh the page

**To Reproduce**
1. Go to donate page
2. approve token
3. reject in your wallet pop-up
4. retry > immediately fails

## Example
[Screencast from 09-01-24 21:29:49.webm](https://github.com/GoodDollar/GoodCollective/assets/6606028/b6ce789c-1976-40a5-8812-0d4436b4c28e)

**Comment by vldkhh** [comment]
verified 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1AwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b117be7bee0fdeb78f289930ae8a3a63ecd529f2/FB066326-43DA-4C3F-8554-1E7935E17E21.MP4)
