### ISSUE TITLE
[UI]: Home Page / Desktop - 1200 breakpoin

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#109]
this breakpoint which is between laptop view and tablet view breaks weird.
i added a design on figma for you to check the behavior 

https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC?node-id=11472:54610&mode=design#663471771

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/6a6ed0ff-c60e-411f-b914-896450f87f48)

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/12aec658-cc73-4798-a7ec-627de19a3053)

**Comment by L03TJ3** [comment]
This is still not 100% fixed @krisbitney 
Reference for various break-point sizing: https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?type=design&node-id=12184-122717&mode=design&t=OOu5l9oDMaB4qjQm-0#679312236

Example video of current behavior:
[Screencast from 24-01-24 20:56:05.webm](https://github.com/GoodDollar/GoodCollective/assets/6606028/a64ff7ea-8dff-4c11-b305-abb23c6d7f8f)


Not included in the vid --> Larger screens should not fill up the entire screen like this:
![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/b7739e48-9a75-4806-85fd-c468e93ee776)

design:
![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/e21534c9-267c-4b08-944d-7ec8abc856f6)

**Comment by krisbitney** [comment]
@L03TJ3 I'll take a look soon

**Comment by krisbitney** [comment]
This is fixed in the open PR https://github.com/GoodDollar/GoodCollective/pull/119

**Comment by L03TJ3** [comment]
@vldkhh this just got merged too dev

**Comment by vldkhh** [comment]
verified
