### ISSUE TITLE
[Design QA] See your impact button text not centered

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#11]
please center the text in See Your Impact Button

Devs:
<img width="506" alt="Screen Shot 2023-08-13 at 14 11 11" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/969625e2-ab6f-479b-a133-1c4f4b5407f4">

Design:
<img width="747" alt="Screen Shot 2023-08-13 at 14 10 55" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/9bd7beab-9d10-45da-a5ba-3c4a06ab6a53">

**Comment by thenerdcat** [comment]
Fixed 
![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/3a6eed43-f63c-423e-9ca3-49e66dc5fc1b)
![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/c6963d47-d8f8-4f09-8b19-ad28d2dbb248)
