### ISSUE TITLE
[UI]:Home Page / Desktop - Excessive gap between cards

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#110]
Gaps between collective cards should be 24px, is to large on desktop now

**Comment by vldkhh** [comment]
verified
 <img width="1540" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTMwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8db4b955187e69402e9e527f0c64f6f55c837d10/image.png" alt="image.png" />
