### ISSUE TITLE
[UI] Complete your donation modal should not have an OK button

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodCollective#115]
dev:
<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9aQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6d7f668036530fafe50c59e90014b3562de7c2e/Screen%20Shot%202024-01-18%20at%2009.48.23.png" alt="Screen Shot 2024-01-18 at 09.48.23.png" />

design:

<img width="657" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOURaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ecbe2eeb93b441ca4a8fce5ce2a1223fe37af79/Screen%20Shot%202024-01-18%20at%2009.50.36.png" alt="Screen Shot 2024-01-18 at 09.50.36.png" />

**Comment by krisbitney** [comment]
Thanks for finding this. I added a fix in https://github.com/GoodDollar/GoodCollective/pull/114. The fix isn't live yet.

**Comment by vldkhh** [comment]
verified, closed
