### ISSUE TITLE
[UI]: containers/modals should not show scrollbars

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#118]
Multiple containers and modals show a scrollbar even if there is nothing to scroll.

**Comment by L03TJ3** [comment]
@vldkhh you have screenshots of the places you noticed this?

@patpedrosa @decentralauren 
Priority?

**Comment by decentralauren** [comment]
@L03TJ3 can determine priority when @vldkhh adds screen shots (cannot tell without images whether it affects UX / ability to navigate significantly).

**Comment by vldkhh** [comment]
@decentralauren @L03TJ3 
collective page:
<img width="1611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3Y3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b46aca94b30daa6ac0fb64084986d71ec70f94e4/Snag_89d7f6.png" alt="Snag_89d7f6.png" />
stewards page:
<img width="1611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3o3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec39bbaf181259244476eac63697e391fbcd3303/Snag_8a3568.png" alt="Snag_8a3568.png" />
donors page:
<img width="1611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzM3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c77eefd52d9560503f129eb5c45f9a9e16de5639/Snag_8a6c47.png" alt="Snag_8a6c47.png" />
complete your donation modal :
<img width="1611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzc3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3803fd2e5950462a707e5250d12d639ed9b7b5c9/Snag_8ac5d1.png" alt="Snag_8ac5d1.png" />
Donation currency and frequency: 
<img width="1611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy83QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8d66197da15a7dd13f026c98af4d38b873feae7/Snag_8b2834.png" alt="Snag_8b2834.png" />
thank you modal:
<img width="1611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEQ3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac6fcd0b76ccbb048eceac822b9d5a2fadd08f1f/Snag_8b6184.png" alt="Snag_8b6184.png" />

**Comment by vldkhh** [comment]
and every single modal that could appears

**Comment by krisbitney** [comment]
Can you please upload the photos directly so I can see them, too? Which browser are you using?

Scrollbars should only appear if content doesn't fit. I see no scrollbars myself. It would help to have more information so I can reproduce the issue locally.

**Comment by decentralauren** [comment]
@vldkhh I'm also unable to see the images. Can you upload directly via the ticket in github (not zenhub) maybe that will solve it?

**Comment by vldkhh** [comment]
@decentralauren @krisbitney how about now?


collective page:
![Snag_14cef52](https://github.com/GoodDollar/GoodCollective/assets/107620432/7023f3ac-ef59-4679-aa49-0b4c11baa98f)

stewards page:
![Snag_14d05b9](https://github.com/GoodDollar/GoodCollective/assets/107620432/2eed58d5-027c-4c19-8260-b88f08e7fb18)

donors page:
![Snag_14d12d8](https://github.com/GoodDollar/GoodCollective/assets/107620432/495d7626-4dc6-450e-aff6-bb00fa24eb75)

complete your donation modal :
![Snag_14d2007](https://github.com/GoodDollar/GoodCollective/assets/107620432/4824fb68-df52-4b7c-8f5c-31c89b076c56)

Donation currency and frequency:
![Snag_14d313d](https://github.com/GoodDollar/GoodCollective/assets/107620432/681ec811-cec2-4c14-a2c1-b64072242014)

thank you modal:
![Snag_14d3fb4](https://github.com/GoodDollar/GoodCollective/assets/107620432/da2cd21b-4b90-45c4-b297-5251aa5e188a)

**Comment by vldkhh** [comment]
@krisbitney Chrome Version 121.0.6167.86 (Official Build) (64-bit)

**Comment by vldkhh** [comment]
@krisbitney Lewis also can't. I noticed that on small screens there is no such issue. Pat and on her MacBook looks fine, I believe Lauren also can't replicate it

**Comment by krisbitney** [comment]
I'm not sure. It would be easier to find a solution if I could replicate the issue. I will do some googling soon and get back to you.

**Comment by L03TJ3** [comment]
![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/88d3c447-50e5-4a92-906f-b1b7a15ad561)

@krisbitney overflow: auto

**Comment by krisbitney** [comment]
@L03TJ3 It's not supported in React Native. It might work on web, but you'll have to change it later for Android/iOS. Is that okay?
<img width="956" alt="Screenshot 2024-01-26 at 10 58 08 AM" src="https://github.com/GoodDollar/GoodCollective/assets/39842820/d92f4109-bfe5-4a61-b322-215da4ac18c4">

**Comment by L03TJ3** [comment]
@krisbitney thats fine, can just suppress with ts-ignore for now

(mvp won't have the android app release any way)

**Comment by krisbitney** [comment]
@vldkhh Can you please tell me if the problem persists in this deployment preview? https://good-collective-plvn065n3-gooddollarteam.vercel.app/

**Comment by L03TJ3** [comment]
Confirmed too so closing
