### ISSUE TITLE
[Design QA] Action log title not centered to icon

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#12]
please center Action Log title to the icon

Devs:
<img width="388" alt="Screen Shot 2023-08-13 at 14 41 45" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/c1ee75fa-679b-470b-8c51-f9fa5e7b06bc">

Design:
<img width="366" alt="Screen Shot 2023-08-13 at 14 41 51" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/7333be34-5979-423e-a95c-51314a0a5dae">

**Comment by thenerdcat** [comment]
Fixed. also fixed the font size 
![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/3fbae8e9-7f41-40b7-bacd-04a88f0f6abe)
