### ISSUE TITLE
[UX/UI]: Transactions list show more

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#124]
How to handle show more button on the transactions list
- [ ] look into lazy loading the transactions
- [ ] should it expand the list?

**Comment by decentralauren** [comment]
@L03TJ3 is this an open item that needs to be assigned to Kris?

**Comment by L03TJ3** [comment]
@decentralauren not sure. is this in scope? then yes, else no it will stay assigned to me I guess

**Comment by decentralauren** [comment]
@krisbitney I've added you to build both the "show more" functionality in web and the lazy load in mobile. We are open to adding a "show more" to both and redirecting to the appropriate page in the explorer.

**Comment by decentralauren** [comment]
Hi @krisbitney - I don't know what notion you're referring to. We're updating the requirements to make them easier for you to implement. The original requirement which was shared in FIgma was for the transactions to load 5 at a time and then lazy load upon scroll. [Here is a link to the comment. ](https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC?node-id=4498:85618&mode=design#483015389)

**Comment by krisbitney** [comment]
I'm referring to the original requirements that were shared with us: https://serota.notion.site/GoodCollective-dApp-MVP-RFP-ba06e28f43e24b85aa336ad7f983c69f

**Comment by decentralauren** [comment]
@krisbitney we were clear with the team that the majority of requirements were documented as comments in the Figma with "Devs." We also walked through these with the team in detail, and you'll notice these comments were there from 7 months ago. I'm sorry that this wasn't handed over to you and explains some of the confusion with how things were implemented.

**Comment by decentralauren** [comment]
We only used the notion to document non-functional requirements or requirements not directly related to the UI. This is why the notion does not include requirements for much of the UI-related flows.

**Comment by krisbitney** [comment]
> @krisbitney we were clear with the team that the majority of requirements were documented as comments in the Figma with "Devs." We also walked through these with the team in detail, and you'll notice these comments were there from 7 months ago. I'm sorry that this wasn't handed over to you and explains some of the confusion with how things were implemented.

Hmm. Okay. Let me talk to dOrg people and see if I can get a better understanding.

**Comment by krisbitney** [comment]
I think I misunderstood what you were asking before

**Comment by krisbitney** [comment]
@decentralauren I think this is what you were asking for? https://github.com/GoodDollar/GoodCollective/pull/168

**Comment by vldkhh** [comment]
@L03TJ3 @patpedrosa @decentralauren  rejected, put it in Sprint

**Comment by krisbitney** [comment]
> @L03TJ3 @patpedrosa @decentralauren rejected, put it in Sprint

Here is a fix for it. Sorry, it was late last night and I didn't check to make sure it worked because it's a simple change.

https://github.com/GoodDollar/GoodCollective/pull/170

It will work with this PR.

**Comment by L03TJ3** [comment]
@vldkhh after qa this one is for product review to determine the initial request of loading more transactions on the page

**Comment by decentralauren** [comment]
@vldkhh has this passed QA?

**Comment by vldkhh** [comment]
@decentralauren from my perspective - yes
