### ISSUE TITLE
[GoodID]: Claim from multiple pools

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#125]
### Description
We want a solution which makes it possible to claim from mulitple pools in one transaction.
For this permission to claim has to delegated/extended to a smart-contract

### Possible solutions
- [ ] Update UBI contract and add additional contract which has given permission to claim from all pools available
- [ ] Connect and address to a existing whitelisted address to be able to claim on behalf of
- [ ] Was there a third?

[Figma file for updated claim flow (dapp and GW1)](https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product?type=design&node-id=13532%3A26790&mode=design&t=mpkGrVC5q8forn5d-1)

**Comment by L03TJ3** [comment]
unstale

**Comment by decentralauren** [comment]
@L03TJ3 do you need any further guidance on this from a UX / requirements perspective? 

Should we link this to the GoodID epic?

**Comment by L03TJ3** [comment]
@decentralauren Just the design ready in figma would be sufficient. This ticket was for doing the smart-contract work which we will not do right now, so likely can be closed

**Comment by decentralauren** [comment]
@L03TJ3 added the figma file for reference (above) and closing
