### ISSUE TITLE
[Bug] Unable to stop donation "Failed to publish payload"

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodCollective#129]
After connecting successfully on mobile iOS using wallet connect, I am unable to stop my donation.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0FQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08cf95589155108b7de6226fd72c19a4f242ab71/RPReplay_Final1706626637.MP4)

**Comment by krisbitney** [comment]
@patpedrosa I'm unable to view this video because it's a private Zenhub link

**Comment by decentralauren** [comment]
@krisbitney I screen recorded her screen recording. [You can see it here :) ](https://www.loom.com/share/53c6fd7b59ee4bfeb7d3225525c774ce?sid=5feb826a-b326-4d4c-9451-634b76dca95e)
