### ISSUE TITLE
[Design QA] transactions text on Transactions Log screen isn't layed out properly

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#13]
transaction date should stick to the right side of the screen

Devs:
<img width="394" alt="Screen Shot 2023-08-13 at 14 43 30" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/568ac694-1b6b-4845-81c9-29a71473591a">

Design:
<img width="372" alt="Screen Shot 2023-08-13 at 14 43 43" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/8a935949-d6c4-437a-88b7-5b5398392761">

**Comment by thenerdcat** [comment]
Fixed ![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/331365f2-8631-4cf6-90f2-640a5233341c)
