### ISSUE TITLE
[Bug] Steward Wallet Collective Card should display same tooltip info as Collective page

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#130]
The text displayed here:
![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/88a6e83b-7d0c-4a3f-980e-869d83c1a60a)

Should match the text displayed here:
![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/c909a134-e33b-4612-9544-90b99f35268e)

**Comment by krisbitney** [comment]
@decentralauren Could you please upload the screenshots directly? I cannot see them.

**Comment by L03TJ3** [comment]
@krisbitney updated

**Comment by krisbitney** [comment]
Fixed in https://github.com/GoodDollar/GoodCollective/pull/141

**Comment by vldkhh** [comment]
@decentralauren the text is matching for Silvi. is it correct?

**Comment by decentralauren** [comment]
@vldkhh yes it is correct. 

@sirpy @L03TJ3 do we have a contract that has this action info to test it displaying when present?

**Comment by L03TJ3** [comment]
@decentralauren the pizza points

**Comment by decentralauren** [comment]
Thanks @L03TJ3!
