### ISSUE TITLE
[Bug] "Go To Profile" on post-donation modal does not navigate to Profile screen

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#134]
![Screenshot 2024-01-30 at 4 11 45 PM](https://github.com/GoodDollar/GoodCollective/assets/149098646/0bcfa636-bdc0-4ba1-bc65-8cc40f1ea308)
Clicking on this modal does not bring me to the Profile screen, I stay on this screen. Please [see video for more information. ](https://www.loom.com/share/a9b616f4a0f642a7b89d09378982264e?sid=8b2bc258-2006-4425-81c1-c65e8eb07e3d)

**Comment by krisbitney** [comment]
I am fairly sure I was told it should automatically navigate to the profile screen once the transaction goes through. Should that still happen?

**Comment by krisbitney** [comment]
This is fixed in https://github.com/GoodDollar/GoodCollective/pull/138

**Comment by vldkhh** [comment]
after the donation, it navigates to the profile. verified
