### ISSUE TITLE
[Bug] Donation flow - error message after confirmation message

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#135]
Receive confirmation modal and then error modal on same transaction. [Please see video for more information.](https://www.loom.com/share/a9b616f4a0f642a7b89d09378982264e?sid=4b65fedb-6da1-48b5-af06-1e29a04f6039)

**Comment by krisbitney** [comment]
The video shows as being 0 seconds long. I'm not sure what happened.

The error "UNPREDICTABLE_GAS_LIMIT" is a smart contract issue.

I'm not sure how or why both the confirmation and error modal could have come up on the same transaction. Forgive me for asking, but was the confirmation modal the one that says "please confirm the transaction" or was it the one that says "thank you for your donation"?

**Comment by decentralauren** [comment]
Sorry @krisbitney - this pointed to the wrong video. [This is the appropriate video. ](https://www.loom.com/share/a9b616f4a0f642a7b89d09378982264e?sid=4b65fedb-6da1-48b5-af06-1e29a04f6039) - let me know if you cannot view it.

There was a "Thank you, you have just donated!" modal followed by a "Something went wrong" "CALL_EXCEPTION" modal about 10 seconds later.

**Comment by L03TJ3** [comment]
@krisbitney 
not sure if I said this in another issue but this flow can have that happen since the 'Thank you, you have just donated' shows after confirming transaction (but it does not wait for it to be completed on the blockchain)

**Comment by krisbitney** [comment]
I think the better approach is to have the Thank You modal indicate that the transaction was submitted, not necessarily that it was confirmed. Or alternatively, it would be better not to automatically navigate to the profile page.

**Comment by decentralauren** [comment]
@krisbitney thank you for clarifying - @L03TJ3 yes we should have another modal. can say:

"Thank you - almost done!
 Your transaction is pending confirmation. Please wait a few moments while it is confirmed."
