### ISSUE TITLE
[Design QA] Space between top Nav Bar elements isn't right

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#14]
space between elements on top bar should be 8px.. now it looks like there's more space

Devs:
<img width="394" alt="Screen Shot 2023-08-13 at 14 50 07" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/94efc447-5bfb-4b0a-864a-72ac04092a2c">

Design: 
<img width="376" alt="Screen Shot 2023-08-13 at 14 49 57" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/6335a292-e942-4113-8527-18bbc54a73b6">

**Comment by thenerdcat** [comment]
Fixed 
![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/07722946-9a20-4e60-a696-af7d4c832097)
