### ISSUE TITLE
[Bug]: Full names shown incorrect

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#140]
The full-names shown on the donor list do not match the address they are applied to

**Comment by L03TJ3** [comment]
fixed here: https://github.com/GoodDollar/GoodCollective/commit/e1825c05914a8e15c369bca736725dfb037f38e5

**Comment by krisbitney** [comment]
> fixed here: [e1825c0](https://github.com/GoodDollar/GoodCollective/commit/e1825c05914a8e15c369bca736725dfb037f38e5)

Thanks!

**Comment by L03TJ3** [comment]
Not fully fixed as it still not maps correctly. Working on that now

**Comment by decentralauren** [comment]
@L03TJ3 does this still need QA?

**Comment by decentralauren** [comment]
@vldkhh can you verify that this was resolved?

**Comment by vldkhh** [comment]
@decentralauren works for me
