### ISSUE TITLE
[Bug] recent transactions doesnt enable to see tx

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#143]
The tx hash is incomplete. copying the tx hash should copy the whole tx or it should link to the explorer
show more also doesnt work correctly but i've seen there's a ticket about it, so not sure if its a bug.

**Comment by sirpy** [comment]
@patpedrosa @decentralauren FYI, please assign.

**Comment by L03TJ3** [comment]
show more button issue is defined here: https://github.com/GoodDollar/GoodCollective/issues/124

**Comment by L03TJ3** [comment]
@decentralauren @patpedrosa 
should we just apply the same what we did for wallet feed?
truncated (first x / last x) and make the tx hash link to the explorer?

**Comment by decentralauren** [comment]
@L03TJ3 the transaction item should link to the explorer. 

Not sure what you mean by "truncated (first x / last x)"?

**Comment by krisbitney** [comment]
> @L03TJ3 the transaction item should link to the explorer.
> 
> Not sure what you mean by "truncated (first x / last x)"?

He means "0x12345...12345" format

**Comment by krisbitney** [comment]
@decentralauren You assigned this to me, but the implementation matches the Figma

<img width="368" alt="Screenshot 2024-02-01 at 10 52 51 PM" src="https://github.com/GoodDollar/GoodCollective/assets/39842820/32170639-9ead-41a1-8739-083e92a8f5b5">

**Comment by krisbitney** [comment]
Fixed in this PR: https://github.com/GoodDollar/GoodCollective/pull/151

**Comment by L03TJ3** [comment]
@vldkhh moved to qa
