### ISSUE TITLE
[Bug] endless re-rendering and fetching of token list

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#145]
When choosing recurring donation with tokens like celo/ceuro (doesnt seem to happen in all tokens)
the console shows endless calls celo token list json

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/9a2c1aa7-007f-47a5-b2fc-ee8ca4732061)

**Comment by krisbitney** [comment]
@sirpy please upload the image directly so I can view it

**Comment by krisbitney** [comment]
Can you also please provide replication steps?

**Comment by krisbitney** [comment]
Fixed here: https://github.com/GoodDollar/GoodCollective/pull/148

**Comment by L03TJ3** [comment]
@vldkhh moved to qa

**Comment by vldkhh** [comment]
verified
