### ISSUE TITLE
[GoodCollective] Revisit Modals after donation - "Please be patient"

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#150]
Update modals to message to user long wait time for donation stream to register / show 

Adding notes from Meri:
- Also in my 1 time donation I still see the text "To stop your donation, visit...)
- In other pop-ups on the app, there is an 'X' in the right corner, allowing me to close them. However, in this particular pop-up, I don't have that option. Neither tapping outside the pop-up nor any other action lets me close it, and I always end up redirected to my profile.
- When I signed my transaction to stop a recurring donation, the process became stuck on the pop-up "Are you sure you want to stop your donation?" It then immediately redirected me to my profile. I didn't receive confirmation that the cancellation was successful; I had to return to the collective to verify that the option to stop donations was no longer available.
- On my profile, I can view the direct donations I've made. However, I'm unsure about recurring donations. I've set up a donation for weekly payments, expecting the initial payment to occur immediately, but I don't see it reflected in my profile. Should I consult the smart contract to determine when the first payment will take place? Additionally, is there a method to review my active donations, or must I visit collectives to check if there's an option to halt donations?

**Comment by L03TJ3** [comment]
@decentralauren that was not @sirpy proposed as alternative.
We can increase polling time around just having a done a TX.

the issue was just this was applied in general and was always polling every second which is what we didn't want.
I don't think need for copy change, just need a more specific polling increase around completing tx's (we do that on gooddapp as well for claiming)

**Comment by sirpy** [comment]
@decentralauren

**Comment by decentralauren** [comment]
Closing as this has been replaced by multiple other issues.
