### ISSUE TITLE
Update post-donation modal to account for lag time

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#159]
Update donation confirmation modal to:

"Thank you - almost done!
Your transaction is pending confirmation. Please wait a few moments while it completes. You will be redirected when it completes."
[
Referencing this closed issue](https://github.com/GoodDollar/GoodCollective/issues/135
)

**Comment by L03TJ3** [comment]
I think this one, #150, #166 should be merged into one
@decentralauren @patpedrosa

**Comment by decentralauren** [comment]
@krisbitney - possible to make the above copy change so that the donation confirmation modal is less confusing?

**Comment by krisbitney** [comment]
> @krisbitney - possible to make the above copy change so that the donation confirmation modal is less confusing?

I am not available for new features beyond the original requirements.

**Comment by decentralauren** [comment]
OK. @L03TJ3 is this a low enough lift for you to take on in the short-term or should we backlog?

**Comment by decentralauren** [comment]
could not reproduce, closing issue.

**Comment by sirpy** [comment]
@decentralauren you dont want to change the text?

**Comment by decentralauren** [comment]
@sirpy I could not get the modal to appear when using the app. If the modal still exists in the latest build then yes, please reopen the issue and update the text.

**Comment by sirpy** [comment]
@decentralauren that's the current modal showing after donating

![image](https://github.com/user-attachments/assets/839d8469-22a7-4f37-b59f-1406dcd58ced)
