### ISSUE TITLE
[Bug] App crashes if connected to wrong chain

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#161]
To reproduce
1. have you metamask connected to xdai (gnosis) chain
2. go to donate
3. connect wallet
4. switch to donate weekly
5. choose celo token

Solution:
App should always request to switch chain to Celo after wallet connection

**Comment by krisbitney** [comment]
Fixed here: https://github.com/GoodDollar/GoodCollective/pull/164

**Comment by vldkhh** [comment]
@sirpy @krisbitney  if connected to the wrong chain - unsupported network is shown. I think its  fine by now 
<img width="1539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXN0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03531cf488f784844bd59a06321f137b55eea54d/Snag_35ee1b38.png" alt="Snag_35ee1b38.png" />

**Comment by L03TJ3** [comment]
@vldkhh I added this as just showing 'None' is not saying anything to anyone
