### ISSUE TITLE
[Feat]: no modal or indication when waiting for TXs

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#166]
After submitting TX there's no feedback to the user to wait.
For example after approving the token in the swap and donate flow there's a wait time until the second TX to donate.
There should be some modal or spinner on the button to indicate to the user something is happening

**Comment by L03TJ3** [comment]
I think duplicate of #150 so either we keep this one, or the other
@decentralauren @patpedrosa
