### ISSUE TITLE
[Bug] recent txs streaming amount will continue endlessly

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#167]
Recent txs shows a stream as an increasing amount
It will continue to show the increasing amount endlessly even if the donation was canceled.
Also If the user updated his donation to a new stream value, it will now show both his TXs as continuously growing amounts, while only one is active.

If you go to https://dev-goodcollective.vercel.app/collective/0x010d572cf7297509f4c3555f8bfb53e6e8d6d54a
You will see that there are multiple streams from the same wallet, but in reality there's only one.

Solution:
Show just the stream flow rate. ie 5G$/Month
The `/Month` is fixed regardless of what the user chose when he created the stream, as the user choice is just a helper for the calculation. All streams are in X/second, in the display we can choose whatever time frame we want.

I've implemented this, which can be merged if approved:
<img width="492" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHdxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7549387167eb5e2ddd9fd4b9b38b752c0d22de4/image.png" alt="image.png" />

With stopped streams
<img width="479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2N3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05d6e1458dc7b9cbea6967593c82ec5535e88ca3/image.png" alt="image.png" />

With stopped streams

**Comment by decentralauren** [comment]
Hi @sirpy . Thank you for this fix, however it will create confusion having all streams appear "per month." What we prefer is a solution that:
- Displays actual streaming cadence chosen by the user (per day / per week / per month)
- For a cancelled stream ("delete flow"), we need to include a third transaction type to indicate that a stream has been cancelled by the user.

**Comment by sirpy** [comment]
@patpedrosa @decentralauren as I've explained, the per week, month, day we show is for calculation help only. All flows are eventually written as x/second.
I would suggest that in the UI stream calculation it would be limited to one time length. Users are used to per month subscriptions.

Ok I'll look into delete op

**Comment by sirpy** [comment]
@decentralauren @patpedrosa 
I've added an example of how a TX description can look when someone stops his stream.
It can show how much in total the stream has donated until it was canceled. and some kind of indication that this is a canceled subscription tx.

Or we can just show that the subcription was canceled without any numbers.

Also similarly you need to decide if you want special indication for stream update. that i've donated at a rate of X/sec but changed it to Y/sec.
So again it can show something like "500G$ donated. subscription updated to 100 G$/Month"
Or just "Updated to 100G$/Month" or "Updated from 50G$/ Month to 100g$/Month"

It's up to you to decide the exact combination. Take into account that the space is limited and need some design update to include longer descriptions.

**Comment by decentralauren** [comment]
Thanks @sirpy this is sufficient for now. Appreciate you working on this. 

I'd like us to change the icon / appearance of the "stream starting" transaction type in this case, so it's clear that this is not a deposit but an indication of a starting stream. @sanajamm @patpedrosa - can we create a "streaming" icon to be used in these events instead of a deposit icon?

**Comment by sirpy** [comment]
@decentralauren what does the "product review" status means?
so this is waiting for further design and product decisions?

**Comment by decentralauren** [comment]
@sirpy Product Review is an optional post-QA step for the product team to make sure something is ready to release. In this case, to determine if this fix is sufficient. Moving this specific ticket back to @vldkhh for QA as things have changed since he last reviewed the functionality. 

I'm creating a new ticket for my note above as it needs further product / design work and should go into the backlog (we can eventually set a "in design" stage in the pipeline pre-backlog if useful).

**Comment by decentralauren** [comment]
@sirpy was this ever implemented? I don't see it in any of the live collectives.

**Comment by sirpy** [comment]
@decentralauren read the comments. You said this need more product design work

**Comment by sirpy** [comment]
@decentralauren or by "sufficient for now" you ment my solution can be merged?

**Comment by decentralauren** [comment]
Hi @sirpy please see [this issue](https://github.com/GoodDollar/GoodCollective/issues/188) which proposes updating transaction types to align with streaming events. Both are assigned to the same epic to improve Superfluid donation usability.

**Comment by sirpy** [comment]
closing in favour of #188
