### ISSUE TITLE
Replace explorer.celo with celoscan

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#169]
I think that celoscan gives a better overview for blockchain data then explorer.celo.

- [ ] - replace usages of explorer.celo with celoscan.io

**Comment by L03TJ3** [comment]
@decentralauren small one for good-collective. not a musthave but imo a 'nice-to-have'
minutes work

**Comment by decentralauren** [comment]
@L03TJ3 ok :) Keeping in backlog

**Comment by vldkhh** [comment]
@L03TJ3 could be closed?

**Comment by L03TJ3** [comment]
yes, is in production
