### ISSUE TITLE
[Bug]: polling causing too many network calls

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#172]
For example in
https://dev-goodcollective.vercel.app/collective/0x010d572cf7297509f4c3555f8bfb53e6e8d6d54a

looking at the network tab there's a call to subgraph every second

please also verify other pages dont have that

**Comment by krisbitney** [comment]
It is not due to endless re-renders. I used polling to keep some values up to date. It's a common useful strategy. Such network requests are inexpensive.

I reduced the poll intervals here: https://github.com/GoodDollar/GoodCollective/pull/173
