### ISSUE TITLE
Link to T&Cs and Privacy Policy from Menu

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#175]
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEV5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--098d4629098ce55a66547ed50530d373a758bd41/IMG_685A997D94D6-1.jpeg" alt="IMG_685A997D94D6-1.jpeg" />

- [ ] Link T&C link to G$ T&C
- [ ] Link Privacy Policy to G$ Privacy policy

**Comment by decentralauren** [comment]
Privacy Policy - https://www.gooddollar.org/privacy-policy#
T&Cs - https://www.gooddollar.org/terms-of-use

**Comment by decentralauren** [comment]
@L03TJ3 another one to pick up if you have time this sprint :)

**Comment by vldkhh** [comment]
verified on feature branch

**Comment by vldkhh** [comment]
verified on prod
