### ISSUE TITLE
[Enhancement] Support One-Time Donations in all Celo-supported Currencies

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#185]
### Issue
Currently only GoodDollar is supported for One-Time Donations, whereas many currencies are supported for streaming. As a result, users interested in making a one-time donation are at a disadvantage (must use other means to swap to G$) and may be discouraged from donating. 

### Fix
-Support swap and payment to pool for One-Time donations in the same currencies that we support for Streaming donations. 

### Technical Implementation
- [ ] Estimate how much work implementing/enabling swap is (max 1 day)
- [ ] TBD
<img width="1054" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejliQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab6da16b361f38071c0297a12ef1afc29018256b/image.png" alt="image.png" />

**Comment by decentralauren** [comment]
Alternate fix to just update copy for now - to discuss w team.

**Comment by L03TJ3** [comment]
@decentralauren what is the todo-item here? the copy update?

**Comment by L03TJ3** [comment]
@decentralauren what is the todo-item here? the copy update?

**Comment by decentralauren** [comment]
@L03TJ3 Ideally we'll update to do the swap for one-time donations. If that's too much work, we can just update the supporting text for one-time donations to say "You can donate using GoodDollars. If you want to donate using another token, please either change to a monthly donation or swap tokens to GoodDollar [link to swap widget in GoodDapp'"

**Comment by decentralauren** [comment]
@sirpy has this been tested? cc @vldkhh

**Comment by vldkhh** [comment]
verified on prod
