### ISSUE TITLE
[UX Enhancement] "Please see smart contract" link to Smart Contract

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#187]
### Issue
On the GoodCollective detail page and Wallet Detail page, when it says, "Please see the smart contract for information regarding payment logic," it would be beneficial to include a direct link to the smart contract. Currently, you have to return to the collective and click on the icon to access it.
![Screenshot 2024-04-15 at 5 00 32 PM](https://github.com/GoodDollar/GoodCollective/assets/149098646/d61b8115-734d-4806-a932-e80eab27a0f5)
![Screenshot 2024-04-15 at 5 00 09 PM](https://github.com/GoodDollar/GoodCollective/assets/149098646/b0667901-a156-4732-ad42-c85a82cad42a)

### Fix
- link to smart contract from this assistive text.

**Comment by sirpy** [comment]
@decentralauren this seems to be conflicting with #209
