### ISSUE TITLE
[Bug] "Claim Celo Domain" shows for wallet with Celo Domain; Celo Domain not displayed

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#190]
### Issue
It suggests that I claim my Celo domain, but I already have one in this wallet.
<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe5cf9dfda6b2f82018b67ced39ced5d745158c0/Captura%20de%20Pantalla%202024-02-02%20a%20las%2019.20.02.png" alt="Captura de Pantalla 2024-02-02 a las 19.20.02.png" />

Wallet address: 0x6823a04a6fd4148167567d5ef6dcca1f34db0494

### Fix
- Implement display of .celo domain name in Wallet Detail / Profile following the below design ([Figma here](https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product?type=design&node-id=4602%3A85963&mode=design&t=nJcKK6VTX8r9D8Rh-1))
- "Claim your Celo Domain" should not show for wallets that have Celo domain(s)
<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE5iQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4d4754690fedf494306f8ef857e68e7a0f7c96f/Screenshot%202024-02-14%20at%2011.19.54%20AM.png" alt="Screenshot 2024-02-14 at 11.19.54 AM.png" />

**Comment by decentralauren** [comment]
We need to investigate the display logic here - I have both a .celo and .eth domain on this wallet however only .eth shows. 
![Screenshot 2024-04-10 at 6 13 22 PM](https://github.com/GoodDollar/GoodCollective/assets/149098646/eff0d0c2-1309-43fa-96eb-02fec6964596)

**Comment by L03TJ3** [comment]
@decentralauren currently we have hardcoded to only fetch .eth

My action item is: verifying that this flow works for CELO chain.

My question to you is: should we show all names, or just celo related ones?

**Comment by decentralauren** [comment]
@L03TJ3 the original requirement was to show the below based on what was have (show the highest priority one available): 

1. Celo domain
2. Eth Domain (show "claim your celo domain" URL)
3. wallet address (show "claim your celo domain" URL)

**Comment by sirpy** [comment]
celo domains are deprecated, the website to buy them doesnt exists anymore, the company that did them pivoted to AI:)

**Comment by sirpy** [comment]
@decentralauren 
see #191 for changes to the profile

**Comment by sirpy** [comment]
celo domains no longer relevant
