### ISSUE TITLE
GoodDollar verification shown for wallet that is not Face Verified

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#191]
### Issue
GoodDollar verification icon is showing for this wallet, which is not Face Verified and should not show as G$ verified. Wallet address 0x94aC950965731f71FA1a1666Beb48216dbA73E09

<img width="827" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00ddb85c60f5746e47337318450f8f5bb01eb31a/Screenshot%202024-04-10%20at%206.13.22%20PM.png" alt="Screenshot 2024-04-10 at 6.13.22 PM.png" />

### Fix

Show GoodDollar verification icon only when connected wallet has passed face verification.

- [x] add a whitelist check to `WalletProfilePage`
- [x] Depending on decision on graph, fetch from their, or call contract

**Comment by decentralauren** [comment]
@L03TJ3 - this bug fix can get picked up in sprint if you have bandwidth.

**Comment by sirpy** [comment]
@decentralauren 
if no ens or G$ profile
<img width="489" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzhvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e82747eefa2e1f71df09ad5823f95afd3babcecd/image.png" alt="image.png" />

have G$ profile but no ens
<img width="459" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11ea666f061620a6028f65268c5ab46e083403f3/image.png" alt="image.png" />

ens no G$ profile
<img width="444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccd9952f321893d494b5b54588f53fde71f989e7/image.png" alt="image.png" />

if has both ens and G$ profile name+ens will be shown without address.
in all cases:
- profile header is clickable and leads to celoscan
- profile image is generated based on wallet address via "robohash.org" - a random robot image based on wallet address

**Comment by decentralauren** [comment]
@sirpy this is great, thank you. Does this also resolve the issue of the G$ "verified" logo only showing for addresses that are FV'd?

**Comment by sirpy** [comment]
@decentralauren yes

**Comment by decentralauren** [comment]
@vldkhh please test (please review comments as this ticket covers more than what was included in the original description).

**Comment by vldkhh** [comment]
@decentralauren @sirpy Doesnt show G$ verified logo for my acc. The account is FV'd - 0xf544B8c1aF11f34FB5aeE37783c2a8BD669b4fEF
<img width="532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWl5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c9e78ce81f3d6d4cb9505aff72a4e2ac60e615b/Snag_187f4e68.png" alt="Snag_187f4e68.png" />

**Comment by decentralauren** [comment]
Thanks @vldkhh - can you move it back to in sprint then, plz?

**Comment by L03TJ3** [comment]
@vldkhh what env is that address whitelisted, and on env did you test this?
(feature branch / goodcollective.xyz / dev-goodcollective?)

**Comment by sirpy** [comment]
fixed on master @vldkhh @L03TJ3

**Comment by vldkhh** [comment]
@sirpy verified on dev 
<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1RqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2be041079abef483972fd9e7aeb144b77b65e8ff/Snag_f70e7c9.png" alt="Snag_f70e7c9.png" />

**Comment by vldkhh** [comment]
verified on prod
