### ISSUE TITLE
Stop Donation button displays after donation stream has ended

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#193]
### Issue
"Stop Donation" still displays after donation streaming is complete. 

Wallet address - 0x7B1a84b6546C7F8fe95fa4E94E4FD1b2eB040165

<img width="1624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--193e720ce274d8d2d06ce2fbfec1461f8facbff8/Screenshot%202024-04-15%20at%207.55.35%20AM.png" alt="Screenshot 2024-04-15 at 7.55.35 AM.png" />

### Fix
Screen state should return to "Donate" button after either streaming period is complete OR user cancels stream

**Comment by sirpy** [comment]
@decentralauren 
this is not a bug, streams are infinite. see #213
