### ISSUE TITLE
Create Segmented UBI pool contract + SDK

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#199]
## Business Description
Create Segmented UBI pool contracts to support the Red Tent UBI MVP, and to act as the initial contracts for the Segmented UBI SDK

## Detailed Description
For the Red Tent Segmented UBI, the following pools should be created. 

### Pool 1: Red Tent Women in Colombia
![RedTent](https://github.com/user-attachments/assets/2e8920f0-4f8f-417c-a904-7099d743dff0)

Pool Description
The Red Tent Women’s Basic Income is designed to flow money unencumbered and unconditionally from women and allies who have it to women who need it. Red Tent’s goal is to create a decentralized, automated and highly personalized system that measures and improves collaboration and wellbeing in communities. Women are the keepers of family and community, yet continue to be disproportionately affected by lack of access to capital and influence in all systems. 

Link to Website: https://redtent.io/ 
_Note: Website will be live for launch.
No other socials to link to._

Pool Parameters
- Maximum 500 members
- Daily Claim Frequency, same time reset as GoodDollar UBI
- [ ] Daily UBI amount TBC (based on G$ price after reserve relaunch)
- $0.0437USD per day (need to translate to G$ after reserve redeployment)

Pool Qualifications
- Gender: Female
- Location: Colombia
- Video Submission: Yes
- All ages

### Pool 2: Red Tent Women in Nigeria
![RedTent](https://github.com/user-attachments/assets/2e8920f0-4f8f-417c-a904-7099d743dff0)

Pool Description
The Red Tent Women’s Basic Income is designed to flow money unencumbered and unconditionally from women and allies who have it to women who need it. Red Tent’s goal is to create a decentralized, automated and highly personalized system that measures and improves collaboration and wellbeing in communities. Women are the keepers of family and community, yet continue to be disproportionately affected by lack of access to capital and influence in all systems. 

Link to Website: https://redtent.io/ 
_Note: Website will be live for launch.
No other socials to link to._

Pool Parameters
- Maximum 500 members
- Daily Claim Frequency, same time reset as GoodDollar UBI
- [ ] Daily UBI amount TBC (based on G$ price after reserve relaunch)
- $0.0437USD per day (need to translate to G$ after reserve redeployment)

Pool Qualifications
- Gender: Female
- Location: Nigeria
- Video Submission: Yes
- All ages

## Technical implementation
- [ ] Create production pools
- [ ] Upload ipfs file with all the details
- [ ] Update documentation

## Acceptance Criteria
- [ ] Pools tested meet criteria above
- [ ] Documentation for SDK complete and published to Github

**Comment by decentralauren** [comment]
@sirpy finalizing this with Galia, but wanted to put on your radar :)

**Comment by L03TJ3** [comment]
@sirpy would be helpful if the claim transaction logs have a claim-event similar to gd-ubi contract

this would make easier to build a 'recent claims' list, based on event has (eg. like done in wallet for otpl events)

**Comment by sirpy** [comment]
@decentralauren do we have tickets on the UI updates required for goodcollective to support this pools?

**Comment by decentralauren** [comment]
@sirpy they are WIP and will be added to the epic that this ticket also belongs to:

**Comment by sirpy** [comment]
@decentralauren 
Also need the following details of the pools 
```
   name: 'Test single donation with swap (Real G$)',
    description:
      'This Collective directly supports smallholder farmers around Kenya’s Kakamega forest. These farmers are acting as nurseries, growing and nurturing native trees to maturity for subsequent reforestation. In partnership with Silvi.',
    email: 'myemail@gmail.com',
    website: 'https://www.silvi.earth',
    twitter: 'https://twitter.com/SilviProtocol',
    instagram: 'https://instagram.com/x',
    threads: '',
    headerImage:
      'https://uploads-ssl.webflow.com/639e611ba0716a170111fe96/65032c75ac7830faf70f9469_FooterBackground.jpg',
    logo: 'https://uploads-ssl.webflow.com/639e611ba0716a170111fe96/65032c4586b18e3e276db342_SilviLogo.png',
    images: [
      'https://uploads-ssl.webflow.com/639e611ba0716a170111fe96/6507cb24ffa8a438ccf13d70_Screen%20Shot%202023-09-17%20at%208.59.00%20PM-p-500.png',
      'https://uploads-ssl.webflow.com/639e611ba0716a170111fe96/650352d39dde89c0fd676908_RuralPlanting.jpg',
    ],
```

**Comment by sirpy** [comment]
@decentralauren notion ticket still not filled

**Comment by decentralauren** [comment]
@sirpy working on it.

**Comment by decentralauren** [comment]
@sirpy updated in description and the notion ticket. Only thing missing is the G$ claim amount per day. Please put a placeholder of 800G$ for now and we will update later.

**Comment by decentralauren** [comment]
@sirpy are the production pools ready? If so I can fund them with a small amount so we can test in prod next week. Please share the contract addresses w @L03TJ3 if so.

**Comment by sirpy** [comment]
done
