### ISSUE TITLE
Clean up GoodCollective pools displayed

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#200]
## Business Description
We need to clean up the pools that display in the GoodCollective dapp in preparation for launch. 

- [x] @decentralauren getting input from Hadar on what pools are what

### Technical implementation
- [x] - Release contracts UBIPool
- [x] - Only show the lastest pools

**Comment by L03TJ3** [comment]
@sirpy This has now been done and released to dev right?
any action points remaining or can the ticket be moved?

**Comment by sirpy** [comment]
@L03TJ3 @decentralauren yes and no.
specifically i think this can be closed.

todo probably in other tickets
1. release new production contracts (currently only dev have been deployed, ie for testing)
2. create new pool for silvi in production
3. update the UI to support ubipools

**Comment by decentralauren** [comment]
@sirpy OK. Do you need a ticket created / tickets updated with this info or will you make the updates?

**Comment by L03TJ3** [comment]
@decentralauren @vldkhh @sirpy 
all the todo's from this one are completed, yes?

**Comment by decentralauren** [comment]
@L03TJ3 yes
