### ISSUE TITLE
Update Donation flow to only support Monthly donations

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#203]
## Business Description
We are updating the donation flow to limit the subscription options to monthly only (removing the options for daily / monthly / yearly). We are doing this because:

- Monthly subscriptions are the most common type of subscription / best match a user mental model of what they might expect from a donation subscription. 
- It improves usability, as we are able to easily display the user's actual donation amount ( G$ x / month OR a one-time donation of G$).

## Detailed Description of Functionality
When the user enters the Donate flow, they are presented with the option to either Donate One-time or Monthly. 

All logic currently in place to display liquidity and insufficient funds messaging should remain. 
This update does not affect in any way the swap functionality.

## Technical Implementation
*_Outline the technical approach for building the feature. This section is typically filled out by the development team or can contain suggestions._ 
(dev team: @johnsmith-gooddollar @sirpy @L03TJ3) 
- [ ] (What api's / sdk's could possibly be used)

## Design Reference
*Link to Figma reference screens & screenshots of key screens*
 
## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: User can choose between one-time and monthly donation options**
  - Given the user is in the donation flow
  - When the user is presented with the donation options
  - Then the user should see the options to donate one-time or monthly
- [ ] **Scenario: Monthly donation amount is displayed correctly**
  - Given the user selects the monthly donation option
  - When the user's donation amount is displayed
  - Then the amount should be displayed as G$ x / month
- [ ] **Scenario: One-time donation amount is displayed correctly**
  - Given the user selects the one-time donation option
  - When the user's donation amount is displayed
  - Then the amount should be displayed as a one-time donation of G$ x
- [ ] **Scenario: Liquidity and insufficient funds messaging remains unchanged**
  - Given the user has insufficient funds or liquidity
  - When the user tries to donate
  - Then the user should see the appropriate messaging as before
- [ ] **Scenario: Swap functionality remains unchanged**
  - Given the user has selected a donation option
  - When the user tries to swap tokens
  - Then the swap functionality should work as before

## Test Cases
*Specify the happy path and unhappy path scenarios to test to verify the feature works as expected.*

**Comment by SanaJamm** [comment]
@decentralauren 

Screenshot:
<img width="405" alt="Screen Shot 2024-05-07 at 9 21 19" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/0e961529-a9b4-49cf-a7b5-3d0c22461ca0">

Figma:
https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product?type=design&node-id=5020%3A87133&mode=design&t=QplIkMw9aiMhuaJD-1

**Comment by vldkhh** [comment]
@sirpy After canceling the monthly donation - Recent Transactions are still increasing streaming amount

**Comment by sirpy** [comment]
@vldkhh pushed a fix. we no longer show streams, just the monthly donation amount
