### ISSUE TITLE
[UI-Bug]: Profile cards break with copy/content

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#205]
### Description
UI is broken on the profile page

### Supporting data
![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/51399aeb-0d6a-415f-911e-05ff8b401382)

**Comment by decentralauren** [comment]
@vldkhh can you retest to see if this is still an issue?

**Comment by sirpy** [comment]
@vldkhh this should be fixed

**Comment by vldkhh** [comment]
verified on prod
