### ISSUE TITLE
[Mobile] Wallet detail page not displaying any transactions

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#207]
All wallet profiles are showing without any activity info (for both donors and stewards) on mobile. 

To reproduce:
* Using mobile browser
* Go to any collective
* Click no any donor or steward wallet
* Observe that no transactions are visible

[Example steward wallet](https://dev-goodcollective.vercel.app/profile/0x52484d481b11fe639c55bbf139702b238ef8ff64)

[Example donor wallet](https://dev-goodcollective.vercel.app/profile/0xc3c54ee8b495a5004602aff40c5880fb8e375aad)

**Comment by decentralauren** [comment]
@vldkhh can you reproduce?

**Comment by vldkhh** [comment]
should be fixed. verified on feature branch

**Comment by vldkhh** [comment]
verified on prod
