### ISSUE TITLE
[Mobile] No collectives loading on homepage

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#208]
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e221925080b52f0c81acf8675e77404c036a8569/image.png" alt="image.png" />

**Comment by sirpy** [comment]
@decentralauren should be working
you can see the old pools at https://goodcollective.vercel.app (new 'production' env)
dev-goodcollective is now our development environment

**Comment by decentralauren** [comment]
Confirmed it all works - thanks @sirpy!
