### ISSUE TITLE
flow rate isnt visible for initial small streams

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#210]
Problem:
When showing donation amounts the amounts of G$/usd are with 2 decimals only.
so the "animation" of the value changing isnt visible ie it is very slow to update.
in the image below i've increased G$ decimals to 4, so the animation is visible and changes every second
of course as a pool gets more and more streams the animation might eventually show.

Solution:
please implement 4 numbers after the decimal, and use
- a lighter font and
- Hex 959090
for the last 2 digits. I can't tell if what's implemented is medium / roman / bold, but if you tell @decentralauren  I can tell you the next lightest font down.

<img width="785" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzdFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae11ebe5085aa16c78ed197c91ce602e6b9af114/image.png" alt="image.png" />

**Comment by decentralauren** [comment]
@sirpy this is fine, though we should be consistent (I see some have 2 or 3 after the decimal point). Thanks for finding a way for it to be visible. 

Why is this assigned to me?

**Comment by sirpy** [comment]
@decentralauren for a decision.
keep it as 2 decimals or increase the decimals and to how many

**Comment by decentralauren** [comment]
@sirpy OK fine - yes per my above message it is fine. Should be 4 decimals (as you mocked up). Please make sure it is always 4 decimals to avoid confusion. 

Is it possible to have the last 2 digits a lighter type font / weight (e.g. light instead of roman)?

**Comment by sirpy** [comment]
its possible, not sure it would look good. just add your decision regarding colors/fonts to use

**Comment by sirpy** [comment]
@decentralauren

**Comment by decentralauren** [comment]
@sirpy please implement 4 numbers after the decimal, and use 
- a lighter font and
- Hex 959090
for the last 2 digits. I can't tell if what's implemented is medium / roman / bold, but if you tell me I can tell you the next lightest font down.

**Comment by decentralauren** [comment]
@L03TJ3 another one to pick up if wanted :)

**Comment by sirpy** [comment]
@decentralauren 
This is how it looks with weight 400.
<img width="470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjhUQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c73aac955a7b3d7096e4777fcd50cdeaf8e1242/image.png" alt="image.png" />

**Comment by decentralauren** [comment]
@sirpy this looks great. Is the color styling tied to the "USD" and other sub-text styling, so that if we update the color it will update both? We may want to make it slightly lighter.

**Comment by sirpy** [comment]
no this is specific for the G$ streams

**Comment by decentralauren** [comment]
@sanajamm will reply with a slightly lighter hex code for the gray.

**Comment by vldkhh** [comment]
verified on feature branch

**Comment by vldkhh** [comment]
verified on prod
