### ISSUE TITLE
add indication to user when data is loading

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#211]
Sometimes we need to wait before allowing user to perform action.
like in the donate screen, when donating in a non G$ currency, we need to calculate the best uniswap exchnage path,
this takes time, until that time the button should be disabled + some kind of indication to user that he needs to wait.

Currently i've added this indication as a Spinner on the button

Todo:
- [ ] choose color/design for indicator
- [ ] check if loading indication is required in other places

<img width="446" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0057ee731954c9a2e67cad4edcfc24cd41635e3b/image.png" alt="image.png" />

**Comment by decentralauren** [comment]
@sanajamm can you please provide guidance for Hadar? Ideally it matches other patterns / styles elsewhere in GoodCollective, Goodwallet and GoodDapp.

**Comment by SanaJamm** [comment]
@sirpy for some reason I can't view the image attached

**Comment by sirpy** [comment]
@SanaJamm are you logged in to zenhub?

![image](https://github.com/user-attachments/assets/84c6e2ef-b244-4979-86bf-fe74769d0c01)

**Comment by decentralauren** [comment]
@sirpy we would like to follow the same pattern as the Uniswap widget in GoodDapp (see animation below), where loading is handling by a combination of 1) a spinner in the widget which presents the info being updated and 2) a button that goes between disabled and enabled based on ability to perform the transaction. 

![Uniswap widget button and loading states](https://github.com/user-attachments/assets/a9bdd348-9499-45c3-9eaa-5769b652fb35)

Do you need any additional assets to make this happen?

**Comment by sirpy** [comment]
i need a design. colors, where exactly the spinner is in our case and its size

**Comment by decentralauren** [comment]
See design in ticket https://github.com/GoodDollar/GoodCollective/issues/218

**Comment by L03TJ3** [comment]
Closing this it will be part of designated buttons
