### ISSUE TITLE
duration for streams is confusing/misleading

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#213]
The stream you create never ends, so if you have more G$s than the amount required for the "duration"
you will still keep on donating G$s.
Duration makes the user think that it is going to end at the end of the duration.

Better explanation or UI is required, also probably different for using G$ directly or using other currencies.

Maybe something like "donate for at least 12 months" and then tell user you dont have any G$s or you need to swap more tokens for the duration.
And a notice that you need to actively cancel the subscription after the duration.

Maybe using the word subscription makes more sense

**Comment by decentralauren** [comment]
@sirpy ok - we had designed with a set duration in mind - so you're saying we should just have people select "Monthly" and have it donate indefinitely (or until they connect their wallet and cancel the stream)?

**Comment by sirpy** [comment]
That's how superfluid streams work. they are indefinite, until the user stops it or run out of funds

**Comment by decentralauren** [comment]
@sirpy we had originally set a duration because we needed to perform a swap for a certain amount of money - I believe that you had advised this as a solution. If streams are indefinite, how dow you suggest we handle the swaps?

**Comment by sirpy** [comment]
I wrote my suggestion in the issue. I just suggest to change the texts/explanations.

**Comment by sirpy** [comment]
@decentralauren

**Comment by decentralauren** [comment]
Working on this with Sana, will revert when ready. https://www.figma.com/design/ihw1PxBvLxacTHnN2aj4lC/3.-Product?node-id=6693-6413&t=cflHzghaHrbL1ltl-1

**Comment by decentralauren** [comment]
Being resolved through updates [via this ticket, ](https://github.com/GoodDollar/GoodCollective/issues/218)so closing.
