### ISSUE TITLE
Bug: after stopping donation modal stays

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#215]
Problem:
* When I confirm the TX to stop donation stream the modal stays
* No confirmation of cancellation 
* After transaction user is redirected to their wallet

<img width="958" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC9KQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26447a68a00dcc764e0ea92334e0efc83368b87b/image.png" alt="image.png" />

Update to:
* After user confirms with their wallet, modal should switch to a spinner/loader until tx is confirmed.
* Once confirmed, Modal should say "Your donation stream has been cancelled." with an "OK" button and X in the corner to dismiss.
* User stays on page and state changes to showing "Donate" button as active again.

**Comment by decentralauren** [comment]
@sirpy yes I agree. Why is this assigned to me?

**Comment by sirpy** [comment]
@decentralauren all issues I assign to you, require decision on UX (spinner? disappear?) + probably a design

**Comment by sirpy** [comment]
@decentralauren

**Comment by decentralauren** [comment]
Updated the description with the appropriate solution.

**Comment by sirpy** [comment]
Added a modal after TX sent, the modal will close once user closes it, or tx is completed.
<img width="741" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODRVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a0e1bb2a0e3159547f7b8e8b082d73acb57165e/image.png" alt="image.png" />

**Comment by vldkhh** [comment]
Fixed, verified on feature branch

**Comment by vldkhh** [comment]
verified on prod
