### ISSUE TITLE
Missing icon for "updated stream"

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#222]
see #188, just the updated stream icon is missing

**Comment by decentralauren** [comment]
@sirpy please find all states here - https://www.figma.com/design/ihw1PxBvLxacTHnN2aj4lC/3.-Product?node-id=18287-79500&t=GF0ewnQ2Q60M2Wio-1
<img width="320" alt="Screenshot 2024-09-09 at 11 29 43 AM" src="https://github.com/user-attachments/assets/fe8a8220-678f-4159-8cc4-35690baeea25">

**Comment by vldkhh** [comment]
verified on feature branch

**Comment by vldkhh** [comment]
@sirpy verified on prod 

<img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzB3Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a234a9a9830885e5fb7957950020ab45686b1bc2/image.png" alt="image.png" />
