### ISSUE TITLE
Update GoodCollective Homepage to include stats & explainer

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#224]
## Business Description
Current GoodCollective home page dumps people into a list of Collectives without any context for where they are or what to do! This update will add a section at the top of the page that describes GoodCollective and offers some quick stats. 

## Detailed Description of Functionality
Users will see this page when they navigate to gooddollar.org/goodcollective or goodcollective.xyz, whether or not they have a connected wallet. The new page contains:

* Header copy
* A short description
* A "How it works" button that links to a sub-page
* A "Donate to a Collective" button which indexes to the Collectives part of the same page (scrolls down)
* A "Create a Collective" button which directs users to our typeform
* Impact Stats, which include: Total # of pools/ Collectives, Total amount of donations (all time), Total # of wallets paid through collectives
* Another header and short description
* A list of all collectives as cards (which link to collective detail pages)

---

## Technical Implementation
- [x] Add header component
- [x] add hook `useSubgraphTotalStats`
- [x] - move create pool button

Nice-to-have:
- [x] where possible and no time-waste, use native-base theming

Awaiting design: 
- [x] How to works redirects

## Design Reference
[Figma link
](https://www.figma.com/design/ihw1PxBvLxacTHnN2aj4lC/3.-Product?node-id=20237-97074&t=x7NiebFUHIJgKXDa-1)

<img width="951" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0t1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b271eadf845c59b9d6dcd3c3e4c89573839b6a8b/Screenshot%202024-09-04%20at%2012.19.13%E2%80%AFPM.png" alt="Screenshot 2024-09-04 at 12.19.13 PM.png" />

 
## Acceptance Criteria
*Specify criteria that will be used to determine if the feature meets the requirements and functions correctly.*

## Test Cases
*Specify the happy path and unhappy path scenarios to test to verify the feature works as expected.*

**Comment by L03TJ3** [comment]
@decentralauren @SanaJamm still need the link for 'how it works'

**Comment by vldkhh** [comment]
verified on feature branch

**Comment by vldkhh** [comment]
verified on prod
