### ISSUE TITLE
Update Donation UI for Streaming Swaps

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#244]
Update Donation Initiation step for Streaming Swaps to be more clear and improve UX. See FIgma files for reference. 

### Design Reference:
https://www.figma.com/design/ihw1PxBvLxacTHnN2aj4lC/3.-Product?node-id=22410-105909&t=raJHlUYBlTBcdf1E-1

<img width="424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdBQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--821f33d6cb8a241aa13426838d6d78ab84185d79/image.png" alt="image.png" />

**Comment by vldkhh** [comment]
verified on prod
