### ISSUE TITLE
Bug: confirm & swap still clickable when insufficient funds etc...

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#247]
Button should be disabled via disabled and not via styles which only changes the look and feel.

**Comment by vldkhh** [comment]
@L03TJ3 The app crashes when clicking on the disabled Confirm button. Doesnt matter one time or streaming.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRaQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7a0e9e83a8ad7239297cf4002d51dd773382494/52250417-E70C-42F6-B006-979308F35F7B.MP4)

**Comment by vldkhh** [comment]
verified on prod
