### ISSUE TITLE
[BUG, GoodCollective] G$ conversion should have comma and only 2 characters after the decimal.

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#259]
G$ conversion should have comma and only 2 characters after the decimal.
![image](https://github.com/user-attachments/assets/2d7c6729-3723-40fa-8b31-ea5b9f641baa)

**Comment by sirpy** [comment]
fixed d0204f4c7e480d0f76d257b3ef96fd163e1b5589

**Comment by vldkhh** [comment]
verified on dev

**Comment by vldkhh** [comment]
verified on prod
