### ISSUE TITLE
[BUGs, GoodCollective] Starting and stopping stream using Celo

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#260]
Starting and stopping stream using Celo, a few issues:
- 0:11 - Starting swap and stream: Metamask launched to start the swap BEFORE I see the modal.
- 1:33 - Had to click the "Confirm" button again after swap to get the Stream transaction to start.
- 2:31 - unable to stop donation stream (keeps crashing metamask). I'm still blocked on this - about to try from Superfluid Dapp

https://gooddollar.slack.com/archives/C07RRC4NQTY/p1733769902866939?thread_ts=1733767326.289819&cid=C07RRC4NQTY
https://gooddollar.slack.com/files/U05U2ULLL0L/F083WK3C5P1/screenrecording_12-09-2024_12-39-36_1.mp4

suggestions - https://gooddollar.slack.com/archives/C07RRC4NQTY/p1733770464035859?thread_ts=1733767326.289819&cid=C07RRC4NQTY

Bugs:
- [ ] ios has different behavior then android. Android expects user to open wallet manually, on IOS the wallet is opened --automatically.
- [ ] the second transaction is not triggering modal + opening wallet
- [ ] Unable to stop donation stream (needs confirmation by @vlad)

**Comment by decentralauren** [comment]
@vldkhh can you please try to reproduce before I prioritize?

**Comment by sirpy** [comment]
@vldkhh

**Comment by vldkhh** [comment]
verified on prod
