### ISSUE TITLE
Donation: Gas price is too high for regular tx

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#29]
Is that something that can be configured on an interface level? Why is it this expensive?

**Comment by sirpy** [comment]
@patpedrosa creating a new stream should cost roughly 0.003 (650k gas * 5gwei gasPrice)

**Comment by decentralauren** [comment]
- one-time send should be a regular "send' transaction on Celo

**Comment by benefacto** [comment]
The donation seemed to expensive and it seems like the base cost is too high; @decentralauren will provide more info

**Comment by L03TJ3** [comment]
https://github.com/GoodDollar/GoodWeb3-Mono/blob/master/packages/sdk-v2/src/sdk/base/hooks/useGasFees.ts

Maybe this can be used/is usefull from sdk-v2 package?
it enforces the baseGwei fee defined by celo protocol

**Comment by sirpy** [comment]
@benefacto in the code where we do TXs it must be hardcoded with 5gwei cast costs.
either in each TX, or if a global setting is possible in whatever web3 framework is used.
see also lewis comment on how we created a hook that enforces that for the useDapp framework

**Comment by L03TJ3** [comment]
@krisbitney 
This one is still existing. suggested gwei from dapp is 10 gwei where 5 is sufficient

**Comment by krisbitney** [comment]
> @krisbitney This one is still existing. suggested gwei from dapp is 10 gwei where 5 is sufficient

Got it. I had thought you guys wrote the `@gooddollar/goodcollective-sdk` package. I changed it there, but you may need to publish a new version on npm before the change is available in the app.

**Comment by L03TJ3** [comment]
@krisbitney once https://github.com/GoodDollar/GoodCollective/pull/111/files is merged i'll trigger the publish

**Comment by krisbitney** [comment]
> @krisbitney once https://github.com/GoodDollar/GoodCollective/pull/111/files is merged i'll trigger the publish

Awesome. Thanks.

**Comment by L03TJ3** [comment]
goodcollective-sdk got released now, didn't really matter from what branch

**Comment by krisbitney** [comment]
> https://github.com/GoodDollar/GoodCollective/pull/111/files

Amazing, thanks. And thank you for updating the branch.

**Comment by vldkhh** [comment]
verified 
<img width="1536" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2ZzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87e8cbcbefbe54d866b3d9f933ec3659e8f2466e/image.png" alt="image.png" />
