### ISSUE TITLE
[Design QA] Top Nav bar/Mobile + Desktop

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#30]
I see that in the top nav bar on Desktop, there's two buttons: WalletConnect and MetaMask, and on mobile it only shows WalletConnect, why is that?

and instead of two buttons side by side, can we add a dropdown button that says Connect Wallet and from there to pick one of them?

Devs:
<img width="376" alt="Screen Shot 2023-11-15 at 11 16 12" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/663dc7c4-1492-4831-9c15-e5cb87f11767">

<img width="1710" alt="Screen Shot 2023-11-15 at 11 15 55" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/7425c1bb-e923-4827-851b-970c34ebb420">

Design idea:

<img width="388" alt="Screen Shot 2023-11-15 at 11 19 40" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/16072147-d4c3-4f46-8e00-cfa47c820aec">

**Comment by benefacto** [comment]
> @benefacto - any idea why we have 2 buttons on desktop and just 1 on mobile? Does Walletconnect on mobile support Metamask?

@decentralauren It seems like it was implemented to have as many buttons as there are connectors ([code reference](https://github.com/GoodDollar/GoodCollective/blob/d425432d7b58e362cc8bd211da5f73a2cb94827b/packages/app/src/components/Header.tsx#L191) for developer context) and it supports two: Metamask & Walletconnect ([code reference](https://github.com/GoodDollar/GoodCollective/blob/d425432d7b58e362cc8bd211da5f73a2cb94827b/packages/app/src/App.tsx#L38)). Why there is one on mobile and two on desktop is unclear at the moment but I'm reaching out to Josh. It's also unclear if WalletConnect 1.x (the version used) supports MetaMask on mobile or whether the reason only one button is displayed is a responsiveness problem. I'm reaching out to Josh for some clarification though.

**Comment by sirpy** [comment]
@patpedrosa @sanajamm @decentralauren @benefacto 
Why can't the "connect wallet" button open the existing frameworks modal that shows different wallet options.
That's a standard and would require less effort

**Comment by krisbitney** [comment]
This is likely why MetaMask is not showing on mobile:

1. The iOS Info.plist and Android AndroidManifest.xml configuration files have not yet been configured to allow the GoodCollective app to detect whether wallet apps like MetaMask are installed. 

2. While the “wagmi” package being used works with React Native, it might not include native connectors for MetaMask out of the box. According to a discussion on the wagmi GitHub, there was no MetaMask connector available for iOS and Android as of October 9, 2023. 

It might make more sense to use a UI component built on top of wagmi to simplify wallet integration. For example, Web3Modal (https://web3modal.com/), a UI SDK made by WalletConnect, has React Native support and works with MetaMask.

**Comment by decentralauren** [comment]
@vldkhh checking to make sure you're tracking with these design QA changes :)
