### ISSUE TITLE
[Design QA] View collective page-recent transactions section / mobile+desktop

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#37]
align icon and title to center 

Devs:
<img width="373" alt="Screen Shot 2023-11-14 at 13 10 52" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/2717ecc7-45ba-401e-a918-29f2d343b457">

**Comment by benefacto** [comment]
## Technical Implementation

To center-align the icon and the title in your `TransactionList` component, you need to adjust the styling of the `row` view that contains these elements. Here's how you can modify the code:

1. **Update Row Style for Center Alignment:**
   Change the `row` style to use `alignItems: 'center'` for vertical alignment and `justifyContent: 'center'` for horizontal alignment. Also, remove the fixed width to allow the row to take the full width of its parent.

   ```javascript
   row: {
     flex: 1,
     flexDirection: 'row',
     alignItems: 'center', // Center items vertically
     justifyContent: 'center', // Center items horizontally
     marginVertical: 8,
     backgroundColor: Colors.white,
   },
   ```

2. **Adjust Row Text Style:**
   The `rowText` style currently has a `marginLeft: 16`. This might need to be adjusted or removed to ensure the text aligns correctly with the icon.

   ```javascript
   rowText: {
     fontSize: 16,
     ...InterSemiBold,
     color: Colors.black,
     textAlign: 'center', // Center the text
   },
   ```

3. **Icon Style:**
   If the icon's style (`firstIcon`) has any margins that affect its alignment, adjust or remove them.

4. **Test on Different Screen Sizes:**
   After making these changes, test your component on various screen sizes to ensure that the alignment appears correctly on both mobile and desktop resolutions.

5. **Check Flex Layout:**
   Ensure that the flex layout behaves as expected in different resolutions. Sometimes, flex properties might need adjustment for different screen sizes.

6. **Remove Unnecessary Width Restrictions:**
   If there are any width restrictions on the `row` or its children that prevent proper centering, adjust or remove them.

By following these steps, the icon and the title in your `TransactionList` component should be centered horizontally and vertically within their row. Remember to test the layout after making these changes to ensure the desired alignment is achieved across different devices and screen orientations.

**Comment by vldkhh** [comment]
verified on web and mobile
