### ISSUE TITLE
[Design QA] View Collective / Desktop - Excessive Padding

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#38]
Horizontal gap between stewards and recent transactions should be set to 32 px

Devs:
<img width="1661" alt="Screen Shot 2023-11-16 at 10 43 48" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/860d60fd-f4ae-4aaf-8207-60f675cf6ff2">

Design:
<img width="765" alt="Screen Shot 2023-11-16 at 10 45 38" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/0376c09d-9321-474a-8f67-5200b3f80e5c">

**Comment by benefacto** [comment]
## Technical Implementation

To set the horizontal gap between the "Stewards" and "Recent Transactions" sections to 32 pixels, you will need to modify the styling of the container that holds these two components. This can be achieved by adjusting the `flexDirection` and `gap` properties in your styles. 

From the provided code, it seems like the `collectiveDesktopActions` style is responsible for the layout of these two sections. Here's how you can modify it:

1. **Update the `collectiveDesktopActions` Style:**
   Adjust the `flexDirection` to `row` (if not already set) and set the `gap` to 32 pixels. This will ensure that there is a 32-pixel gap between the two horizontally aligned components.

   ```javascript
   collectiveDesktopActions: {
     flex: 1,
     flexDirection: 'row', // Ensure the components are aligned in a row
     justifyContent: 'space-between', // Adjust as needed for your layout
     gap: 32, // Set the gap between elements to 32 pixels
     // Other styles...
   },
   ```

2. **Adjust Child Component Widths:**
   If the child components (`StewardList` and `TransactionList`) have fixed widths or maximum widths set, ensure that they accommodate the 32-pixel gap within the total container width. You might need to adjust their widths accordingly.

3. **Test on Different Screen Sizes:**
   After making these changes, test your component on various screen sizes to ensure that the layout appears correctly and the gap is consistent across different devices.

4. **Check for Conflicting Styles:**
   Ensure that no other styles are conflicting with or overriding this layout adjustment. This might include checking parent or child component styles.

5. **Consider Responsive Design:**
   If the layout needs to change for different screen sizes (like mobile vs desktop), consider using media queries or platform-specific styling to adjust the layout accordingly.

By following these steps, you should be able to set the horizontal gap between the "Stewards" and "Recent Transactions" sections to 32 pixels in your `ViewCollective` component. Remember to test the layout after making these changes to ensure the desired alignment is achieved across different devices and screen orientations.

**Comment by vldkhh** [comment]
@krisbitney still reproduces, please re-check. My resolution is 1920x1080
 <img width="1542" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlIvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36a366b68627162cbad7722459edb63dcb2d631c/image.png" alt="image.png" />

**Comment by krisbitney** [comment]
> @krisbitney still reproduces, please re-check. My resolution is 1920x1080 <img alt="image.png" width="1542" src="https://camo.githubusercontent.com/f50050609c8c4ebce8cfd73a0d6e40dd24d95a59c3c5323d017611269102e085/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424e6c49765157633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d333661333636623638363237313632636261643737323234353965646236336463623264363331632f696d6167652e706e67">

Apologies for this. It should be fixed by this PR: https://github.com/GoodDollar/GoodCollective/pull/62

**Comment by krisbitney** [comment]
@vldkhh Please QA this when you have a few minutes

**Comment by L03TJ3** [comment]
@vldkhh is an older one but still has to be qa'd

**Comment by vldkhh** [comment]
fixed

**Comment by krisbitney** [comment]
Closing as completed, based on @vldkhh 's comment
