### ISSUE TITLE
[Design QA] Donation page/Desktop - Breadcrumbs Missing

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#40]
Add breadcrumbs to page

**Comment by decentralauren** [comment]
![Screenshot 2023-11-21 at 10 31 16 AM](https://github.com/GoodDollar/GoodCollective/assets/149098646/1e83779c-2985-445c-b69f-608aa421e1f5)

**Comment by benefacto** [comment]
## Technical Implementation

To add breadcrumbs to the `DonateComponent`, you'll need to integrate the `Breadcrumb` component into it. This will allow users to see their current location within the application and navigate back to previous pages easily. Here's how you can do this:

1. **Import the `Breadcrumb` Component:**
   Make sure that the `Breadcrumb` component is imported into your `DonateComponent`.

   ```javascript
   import Breadcrumb from './Breadcrumb';
   ```

2. **Add the Breadcrumb Component to the Render Method:**
   Place the `Breadcrumb` component at the top of the `DonateComponent`'s render output, so it appears under the "GoodCollective" header.

   ```javascript
   function DonateComponent({ 
     // ... props ...
   }) {
     // ... component logic ...

     return (
       <View style={[styles.body, isDesktopResolution && styles.bodyDesktop]}>
         <Breadcrumb currentPage="Donate" />

         {/* Rest of your component code */}
       </View>
     );
   }
   ```

3. **Pass the Current Page as a Prop:**
   The `currentPage` prop can be dynamic based on the current page's context. For the `DonateComponent`, you can simply pass `"Donate"` as the `currentPage` prop, or any other relevant string that represents the current page in the breadcrumb.

4. **Style Adjustments:**
   Adjust the styles of the `Breadcrumb` component if necessary to match your design requirements. This includes positioning, color, font size, etc.

5. **Responsive Design Consideration:**
   If the breadcrumb needs to be displayed differently on various screen sizes, use `useMediaQuery` within `Breadcrumb` or conditionally render different styles or layouts in the `DonateComponent`.

By following these steps, you will integrate a breadcrumb navigation into your `DonateComponent`, enhancing the user experience by providing a clear path of navigation and easy access to previous pages. Remember to test the integration on different devices and screen sizes to ensure consistent behavior and appearance.
