### ISSUE TITLE
Subgraph is down

### ISSUE THREAD

**Issue by benefacto** [GoodDollar/GoodCollective#42]
```
index-3f0a3c7f.js:233 ApolloError: indexing_error
    at new a (index-3f0a3c7f.js:200:184)
    at g.toQueryResult (index-3f0a3c7f.js:206:11615)
    at g.useQuery (index-3f0a3c7f.js:206:7413)
    at useLazyQuery (index-3f0a3c7f.js:206:12360)
    at useCollectiveData (index-3f0a3c7f.js:233:70)
    at HomePage (index-3f0a3c7f.js:237:9757)
    at Xh (index-3f0a3c7f.js:38:20960)
    at dj (index-3f0a3c7f.js:40:3318)
    at Wk (index-3f0a3c7f.js:40:47416)
    at Vk (index-3f0a3c7f.js:40:42128)
(anonymous) @ index-3f0a3c7f.js:233
index-3f0a3c7f.js:237 undefined
index-3f0a3c7f.js:233 ApolloError: indexing_error
    at new a (index-3f0a3c7f.js:200:184)
    at index-3f0a3c7f.js:204:99107
    at b0 (index-3f0a3c7f.js:199:10095)
    at index-3f0a3c7f.js:199:10002
    at new Promise (<anonymous>)
    at Object.then (index-3f0a3c7f.js:199:9967)
    at Object.next (index-3f0a3c7f.js:199:10109)
    at notifySubscription (index-3f0a3c7f.js:199:2415)
    at onNotify (index-3f0a3c7f.js:199:2926)
    at a.next (index-3f0a3c7f.js:199:3560)
```
This is blocking additional development and @Joshua-Jack is working on resolving it.

**Comment by benefacto** [comment]
Fix did not resolve the issue. It might be worth getting the subgraph working locally to start pushing some of the features forward.

**Comment by L03TJ3** [comment]
@benefacto @sirpy 
is this just a local issue? is this a specific subgraph issue which should be reported to them?

**Comment by benefacto** [comment]
> @benefacto @sirpy is this just a local issue? is this a specific subgraph issue which should be reported to them?

@L03TJ3 This was an issue with [the hosted subgraph](https://api.studio.thegraph.com/query/50925/goodcollective/v27) currently used in [the latest preview environment](https://good-collective-bpqwxv080-gooddollarteam.vercel.app/). I just rechecked and it looks like it's back up again, though, but I'm not aware of what change @Joshua-Jack may have made to bring it up again.

**Comment by benefacto** [comment]
I spoke too soon. It looks like the indexing errors are now not occurring on the main page but on the subpages.
Main collective page loads:
![image](https://github.com/GoodDollar/GoodCollective/assets/10215679/992b135e-ab1e-48ee-926b-6cfc6b0a2dec)
But click on any collective and you'll note that `indexing_error` is still occurring. Further debugging within the subgraph is needed (this is not an Apollo side issue):
![image](https://github.com/GoodDollar/GoodCollective/assets/10215679/9ae9ccf6-f211-47a1-a6f7-8b19a9dca399)

**Comment by benefacto** [comment]
> indexing errors are now not occurring on the main page
Indexing errors are back on the main page again:
![image](https://github.com/GoodDollar/GoodCollective/assets/10215679/77c3b216-1c7a-440d-9dd8-1f0abb53aba8)

**Comment by benefacto** [comment]
Deployment steps:
1. prepare script
2. prepare:celo (includes an auth key secret that should probably be removed)
3. build:copyabi or yarn codegen to pull updated ABIs

**Comment by benefacto** [comment]
Next steps:
- @sirpy may publish the subgraph publicly so that the errors are accessible to more than the account who owns it
- @benefacto to debug the subgraph errors as needed or otherwise proceed on other work (which a working subgraph should unblock)

**Comment by benefacto** [comment]
This issue should now be resolved with the new, indexed subgraph. Feel free to verify at the latest preview deployment: https://good-collective-7ssf2sna9-gooddollarteam.vercel.app/

**Comment by benefacto** [comment]
> @benefacto it still reproduces for me. You can see the link above in the picture <img alt="image.png" width="1522" src="https://camo.githubusercontent.com/df9266f1d6ae8ee15023595f1aaef1c502bade4f3991462eed7a4b009c30676f/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424c3273775157633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d373734346661666132353231353033356435623831313339326466636136353665333864353365322f696d6167652e706e67">

@vldkhh The image you attached does not bear relevance to this ticket.
![image](https://github.com/GoodDollar/GoodCollective/assets/10215679/7ab9cc7f-375e-4241-a040-9e49beb1ee68)
This image signifies different errors which may or may not be affecting the app and might warrant further investigation.
Since you can navigate to the donation page, this signifies that the subgraph is back up as expected.

**Comment by krisbitney** [comment]
What is the status of this?

**Comment by vldkhh** [comment]
@krisbitney fixed

**Comment by krisbitney** [comment]
Awesome. Is it okay to close the issue?
