### ISSUE TITLE
Connect wallet button should open web3modal

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#50]
Currently only metamask and walletconnect are supported

There are standard solutions for connecting wallets and we should use them.
web3modal is already installed and demonstrated in the original code.

**Comment by krisbitney** [comment]
I was just trying to implement this but there is an issue. The react-native version of Web3Modal doesn't support web, and the ReactJS version doesn't support React Native. 

The current solution uses `wagmi`, which is the basis of Web3Modal. Are there particular wallets you have in mind that you want to support?

**Comment by krisbitney** [comment]
Is this the code you're referring to that is supposed to demonstrate use of Web3Modal? https://github.com/GoodDollar/GoodCollective/blob/web3Integrations/packages/app/src/hooks/useWeb3Modal.tsx

**Comment by vldkhh** [comment]
verified
