### ISSUE TITLE
Hard coded values should be dynamic

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodCollective#52]
Hard coded values like G$ price should be dynamic

I've noticed some places are already marked with a TODO
but need to go over code and find all fixed addresses and values and verify if they should be dynamic or not

https://github.com/GoodDollar/GoodCollective/blob/895376361b63b5077ddc875f17b193cc98948663/packages/app/src/components/DonateComponent.tsx#L72

**Comment by decentralauren** [comment]
@sirpy can you do a short screen recording or share links for how to do the minting?

**Comment by sirpy** [comment]
@decentralauren its in the sdk folder readme

**Comment by L03TJ3** [comment]
@sirpy @decentralauren @krisbitney 
is there anything left over for todo?

**Comment by krisbitney** [comment]
> @sirpy @decentralauren @krisbitney is there anything left over ffor this ticket?

I don't think so. There isn't anything that I'm aware of.

**Comment by sirpy** [comment]
@L03TJ3 @krisbitney 
All todos have been closed?
Do a manual code search for "0x..." maybe we still have some left hard coded addresses.

**Comment by L03TJ3** [comment]
yes thats why I assigned myself and what I wanted to do @sirpy

**Comment by krisbitney** [comment]
@L03TJ3 Would you consider this issue completed? It looks like your PR is changing how immutable constants are handled, not dynamic values, so I don't think it's related to this issue.

**Comment by L03TJ3** [comment]
@krisbitney see my last comment there. So yes this is closed
