### ISSUE TITLE
[BUG] User unable to to directly donate G$

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#53]
Steps: 
1) connect wallet with G$ available
2) go thought the donation flow
3) click on the donate button
4) sigh tx in wallet 
5) observe the result

Actual result:
The transaction has been reverted

Expected result:
The transaction has been completed 

Environment:
https://good-collective-72ntzd8nf-gooddollarteam.vercel.app/donate/0x11f18e8f2a27d54a605cf10486b3d4c5aeeba81f

Devices: 
Should reproduce everywhere (iOS/Android/desktop)

Attachments:
<img width="1595" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3BUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7cc088fb7ed976e0cc0521e2aef4265cd03de75/Snag_6e1952bf.png" alt="Snag_6e1952bf.png" />

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed72077ee1cafed38cbc7901ede46cc1dd56cb2f/AF95473B-2053-4575-B50E-4C2E6F0C588B.MP4)

**Comment by decentralauren** [comment]
@vldkhh is this still open?

**Comment by vldkhh** [comment]
verified
