### ISSUE TITLE
[Design QA] Extend Connect Wallet button on Top Nav

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodCollective#7]
**Describe the issue**
The connect button looks decentralized because it's not extending properly.

Dev:
<img width="365" alt="Screen Shot 2023-08-10 at 12 13 24" src="https://github.com/GoodDollar/GoodCollective/assets/49105975/a124d4ac-92eb-46f2-b707-02e244918af4">

Design:
<img width="323" alt="Screen Shot 2023-08-10 at 12 13 13" src="https://github.com/GoodDollar/GoodCollective/assets/49105975/9748288c-4a18-4f5d-8e1d-6d663983f8fb">

**Comment by thenerdcat** [comment]
Fixed 
![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/01d50e46-9f33-4639-83c6-dee2a9b5b690)
