### ISSUE TITLE
how to get the first and last name of users?

### ISSUE THREAD

**Issue by krisbitney** [GoodDollar/GoodCollective#76]
The UI design suggests there is an intention of using user first and last names. How would these be obtained?

**Comment by sirpy** [comment]
You will need to query the mongodb backend.
Results should be cached if exists and not query the backend again for a while.
if need to fetch multiple names then queries should be in parallel, ie using `await promise.all`
I'll provide credentials on slack
```
walletHash = keccack256(walletAddress)
findOne({"index.walletAddress.hash":walletHash},{"fullName.display":true})
```

**Comment by krisbitney** [comment]
After a few hours of looking into this, I learned that you will need to create a MongoDB Realm to query from the browser

The `mongodb` package is a NodeJS package

I have a looked for another way, but it seems you need to either create a Realm or run a NodeJS server

**Comment by krisbitney** [comment]
resolved in https://github.com/GoodDollar/GoodCollective/pull/113
