### ISSUE TITLE
Add action labels

### ISSUE THREAD

**Issue by krisbitney** [GoodDollar/GoodCollective#78]
The UI design has what I would call "action labels", e.g. `Stewards get G$ 800 each time they log a tree's status.`. How can these be obtained?

**Comment by sirpy** [comment]
@decentralauren @patpedrosa please assist

I'm guessing this has to be part of the fixed attributes of the project

**Comment by decentralauren** [comment]
@sirpy @krisbitney correct. This is a fixed attribute per project (like the description and social URLs)

**Comment by krisbitney** [comment]
How would I obtain the attribute?

**Comment by sirpy** [comment]
@krisbitney from the json file you parse from ipfs
add another attribute if it is missing.

**Comment by krisbitney** [comment]
> @krisbitney from the json file you parse from ipfs add another attribute if it is missing.

I can add an optional attribute `actionLabel`. What should I use when that attribute is missing?

**Comment by krisbitney** [comment]
Based on https://www.notion.so/Pilot-dApp-Collective-Content-98cd3c62a39b4c7b9a8e066f14b6074e, I added a property `infoLabel`.

In the UI, I use a default statement if `infoLabel` is missing.

```ts
const infoLabel = collective.ipfs.infoLabel ?? 'Stewards get G$ each time they complete an action.';
```

**Comment by krisbitney** [comment]
@sirpy @decentralauren I believe this is completed

**Comment by L03TJ3** [comment]
@decentralauren @patpedrosa 
what should be confirmed is the default copy if no info label is defined

**Comment by decentralauren** [comment]
@L03TJ3 In the event that this value is blank, we should display: "Please see the smart contract for information regarding payment logic."

**Comment by krisbitney** [comment]
> Please see the smart contract for information regarding payment logic.

Fixed in https://github.com/GoodDollar/GoodCollective/pull/132

**Comment by decentralauren** [comment]
Thanks @krisbitney!

**Comment by krisbitney** [comment]
@decentralauren yes, I had forgotten that the default label is also used in the user profile. The fix for that has been added to the other PR.

**Comment by decentralauren** [comment]
Thanks @krisbitney
