### ISSUE TITLE
Determine if stewards are verified

### ISSUE THREAD

**Issue by krisbitney** [GoodDollar/GoodCollective#79]
The UI design suggests a verification label should be added to verified stewards. How would we determine whether a steward is verified?

**Comment by sirpy** [comment]
by checking the identity contract. there should be an sdk in goodweb3-mono sdk-v2 package
https://github.com/GoodDollar/GoodWeb3-Mono/blob/a99851109e6041911dc876d59783679f12272445/packages/sdk-v2/src/stories/claim/IdentityHooks.stories.tsx#L16

@L03TJ3 is sdk-v2 setup to be used in goodcollective?

**Comment by L03TJ3** [comment]
@sirpy it is already being used

**Comment by krisbitney** [comment]
@sirpy @L03TJ3 Thanks!

**Comment by krisbitney** [comment]
@sirpy @L03TJ3 I believe this is completed

**Comment by decentralauren** [comment]
@sirpy per Pat's message above can you help us trigger a payment to the verified address she shared so we can test the GoodDollar verification displaying?

**Comment by sirpy** [comment]
@decentralauren @patpedrosa 
i'll work with @L03TJ3 for a quick solution to mintNFT

**Comment by decentralauren** [comment]
@vldkhh this should move back to QA (needs to be retested after hadar and lewis work on it).

**Comment by decentralauren** [comment]
Assigned @L03TJ3 - please ping us when this is ready for review!

**Comment by L03TJ3** [comment]
@L03TJ3 add to donors list + add gd wallet as steward

**Comment by decentralauren** [comment]
@L03TJ3 LMK if this is still open with meaningful work to do - if so we can put into next sprint / move back into To Do status :)

**Comment by decentralauren** [comment]
@vldkhh to retest when you're able!

**Comment by L03TJ3** [comment]
replaced by: https://app.zenhub.com/workspaces/goodlabs-61559a6a33275e00141f8ee4/issues/gh/gooddollar/goodcollective/191
