### ISSUE TITLE
[Design QA] Extend Connected Wallet Component on Top Nav

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#8]
Connected Wallet and balance component should extend with screen and keep an 8px space from the the menu button (also 8px distance between network and balance)

Devs: attached are different screens sizes with the current problem:

<img width="501" alt="Screen Shot 2023-08-13 at 12 30 32" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/6969322e-a3ec-4c84-9a17-a9ef5448bb51">

<img width="464" alt="Screen Shot 2023-08-13 at 12 30 43" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/5c45e359-9911-4892-ae62-5168f18270f4">

Design:

<img width="374" alt="Screen Shot 2023-08-13 at 12 37 17" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/7f10ed14-aa10-422c-ab04-24041bb840d5">

**Comment by thenerdcat** [comment]
Fixed. 
![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/abe2e27f-eaf4-4006-9146-93914ade0bbb) 
![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/12130c11-2046-4ddf-b466-e5c46faa62a6)
