### ISSUE TITLE
set price impact threshold

### ISSUE THREAD

**Issue by krisbitney** [GoodDollar/GoodCollective#83]
The current threshold for warning users of an unacceptable swap price impact is set to 5%. Please feel free to suggest an alternative threshold.

- [ ] - Should be able to be set by user
- [ ] - default value is ??

**Comment by vldkhh** [comment]
@patpedrosa @decentralauren

**Comment by decentralauren** [comment]
Default value for warning should be 5%.
CTA button should display as active (not inactive / gray) when warning is present.

**Comment by krisbitney** [comment]
> Default value for warning should be 5%. No need for user to set. CTA button should display as active (not inactive / gray) when warning is present.

In that case, no further changes need to be made. That is the current state.

**Comment by L03TJ3** [comment]
Confirmed that this is currently working as described above on dev. so closing
