### ISSUE TITLE
Donation and swap execution hooks have some redundant validation logic 

### ISSUE THREAD

**Issue by krisbitney** [GoodDollar/GoodCollective#84]
consolidate the repeated lines of code in those hooks

Reference (example of the flow in one of the hooks: https://github.com/GoodDollar/GoodCollective/blob/3cae03228a3e6a08920181525a1a62c1c4de6c99/packages/app/src/hooks/useContractCalls/useSupportFlow.ts#L24

this should be handled by a simple helper or hook

**Comment by L03TJ3** [comment]
@krisbitney  are we talking about the same thing here? #85

**Comment by krisbitney** [comment]
> @krisbitney are we talking about the same thing here? #85

yes, exactly

**Comment by L03TJ3** [comment]
@krisbitney will you still take this one on or shall I assign myself?

**Comment by krisbitney** [comment]
> @krisbitney will you still take this one on or shall I assign myself?

It was already done and merged awhile ago

**Comment by L03TJ3** [comment]
yes this was part of the bigger BugFixes PR. so closing
