### ISSUE TITLE
[UI] Profile (Donors) show reflect sum of stewards of each collective supported

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#88]
i.e. 
“Wonderful's funding supported {sum of all stewards paid from x collectives}”
“Towards this collective, supporting {# stewards paid in that collective}”

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/7d883df3-a0d3-4af7-b825-15fe92da764b)

**Comment by decentralauren** [comment]
related to[ this question](https://github.com/GoodDollar/GoodCollective/issues/75) from @krisbitney - captured as a to-do in ticket [81](https://github.com/GoodDollar/GoodCollective/pull/81)
