### ISSUE TITLE
[UI] Collective Page - Display Pool Balance

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#89]
_1) Should always link to the main smart contract for the collective_ - this already captured[ in ticket 103](https://github.com/GoodDollar/GoodCollective/issues/103)

2) Should show the main token balance for that contract

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/d592fd7f-6d20-414d-92eb-f1d6cb05a772)

**Comment by krisbitney** [comment]
> 1. Should always link to the main smart contract for the collective
> 2. Should show the main token balance for that contract
> 
> <img alt="image.png" width="1900" src="https://camo.githubusercontent.com/e659db2c640946703d62c458f35d2c8370ef12ce7b5f31af52f8b926121a50c9/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424e4735435157633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d633664313261373034333537633632346334663632346162633231666564383732633937323538652f696d6167652e706e67">

The image link appears to be broken

**Comment by decentralauren** [comment]
Captured in @krisbitney [ticket 81](https://github.com/GoodDollar/GoodCollective/pull/81)

**Comment by L03TJ3** [comment]
@krisbitney are both points tackled in https://github.com/GoodDollar/GoodCollective/pull/81 ?

**Comment by krisbitney** [comment]
> @krisbitney are both points tackled in #81 ?

point 1 is fixed in https://github.com/GoodDollar/GoodCollective/pull/111

**Comment by L03TJ3** [comment]
@L03TJ3

**Comment by krisbitney** [comment]
I believe this issue is completed

**Comment by vldkhh** [comment]
verified
