### ISSUE TITLE
[Design QA] Create  a Collective button doesn't extend properly

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#9]
Create a Collective button should fill the width of the screen and not leave space.

Devs: 
<img width="381" alt="Screen Shot 2023-08-13 at 13 26 21" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/f15ad081-d0ca-46f5-af7a-97bd2e7f819a">

Design:
<img width="374" alt="Screen Shot 2023-08-13 at 13 27 14" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/03842ef5-e2c0-4ba6-af4b-2dee3da5244e">

**Comment by thenerdcat** [comment]
![image](https://github.com/GoodDollar/GoodCollective/assets/80982814/e90026e3-55a1-414a-a9c2-97feae9975b4) this is working fine in the develop and QA-design branches
