### ISSUE TITLE
[BUG] After my first donation, the redirect to my profile shows an empty profile page and it's missing top nav bar

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#95]
[BUG] After my first donation, the redirect to my profile shows an empty profile page and it's missing top nav bar

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/27ffde80-60b0-4f82-9490-0f16842d0ca2)

**Comment by krisbitney** [comment]
A fix for the empty profile issue is in a PR. 

I can't see the image and I'm not sure what you mean by missing top nav bar. Could you please clarify?

**Comment by krisbitney** [comment]
Yes, those images load. Thanks!

**Comment by vldkhh** [comment]
verified
