### ISSUE TITLE
[BUG/UI] Error modal too large for viewport

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#97]
- [ ] Error modal should be using generic modal from good-design
- [ ] should apply good-collective theme

![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/aab4efbc-02a5-4c18-ab1d-b8302328bfb6)

**Comment by L03TJ3** [comment]
@L03TJ3: should be part of generic modals

**Comment by krisbitney** [comment]
This should be fixed

> @L03TJ3: should be part of generic modals

This should be fixed already

**Comment by L03TJ3** [comment]
@krisbitney this was not a comment to you but for myself. Sorry should have clarified

**Comment by L03TJ3** [comment]
this issue is solved and generic modals will be handled later/defined in other issue
